### ISSUE TITLE
雷达怎么设置？

### ISSUE THREAD

**Issue by JiangWeiHn** [chengwei0427/Lidar_IMU_Localization#13]
我用的是速腾的雷达，我看map_manager.h里的参数直接写死了，如：
  int laserCloudCenWidth = 10;
  int laserCloudCenHeight = 5;
  int laserCloudCenDepth = 10;

  int laserCloudCenWidth_last = 10;
  int laserCloudCenHeight_last = 5;
  int laserCloudCenDepth_last = 10;

  static const int laserCloudWidth = 21;
  static const int laserCloudHeight = 11;
  static const int laserCloudDepth = 21;
还有好多地方直接写了4851，这些需要修改吗？不太明白。期待您的回复。

**Comment by chengwei0427** [comment]
这里不需要修改；具体可以参考的loam_velodyne;

**Comment by JiangWeiHn** [comment]
谢谢
