### ISSUE TITLE
定位方法以及建图端pcd保存

### ISSUE THREAD

**Issue by thomaswangbin** [chengwei0427/Lidar_IMU_Localization#2]
你好，有两个疑问：
1.定位部分是分成基于地图的定位和基于LIO的两种模式吗，这两种模式是分开的吗？
2.定位加载的那几个pcd文件具体格式是啥，比如将姿态的三个角度信息放在normalxyz里，关键帧的索引放在intensity？

**Comment by chengwei0427** [comment]
Hi, @thomaswangbin ,

1. 定位中存在两种约束，一种是基于地图的先验约束，一种是LIO约束；
2. 用intensity存放keyframe索引，具体格式，建议你看下代码；
