### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by zhu-bingo** [chengwei0427/Lidar_IMU_Localization#3]
ROOT_DIR: /home/zzy/fast_lio2/src/Lidar_IMU_Localization-main/
file dir: /home/zzy/LOAM_58
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
99646, 35754

**Comment by chengwei0427** [comment]
Hi, @zhu-bingo 

     Thanks for your attention. It's ok for the coud type, you can ignore the msg.

```
typedef pcl::PointXYZINormal PointType;
typedef pcl::PointCloud<PointType> CLOUD;
typedef CLOUD::Ptr CLOUD_PTR;
```

**Comment by boboxu1015** [comment]
what?
