### ISSUE TITLE
nonfeature error on neotic

### ISSUE THREAD

**Issue by Lonelyf** [chengwei0427/Lidar_IMU_Localization#4]
when i start the mapping launch on noetic, i got an error message on poseEstimate:
Estimator::FeatureNon::ComputeError(Eigen::Matrix<double, 4, 4, 0, 4, 4> const&)()

I don't know why it would happened when I debug the code, and couldn't find the resean.

please help me, thanks!

**Comment by chengwei0427** [comment]
Hi， @Lonelyf 

Thanks for your attention.

You can comment the part of non-feature, for the reason the feature extract node donot publish the non-feature.
