### ISSUE TITLE
你好，请问定位精度有多少呀

### ISSUE THREAD

**Issue by LiquoriceH** [chengwei0427/Lidar_IMU_Localization#5]
作者你好，请问定位精度有几cm呢，还有就是doc中的lio_xyz中的图例TUM是什么意思呢，三次测试的数据吗

**Comment by chengwei0427** [comment]
你好， @LiquoriceH 

感谢关注！

定位精度没有进行评测，没有找到这个数据集的真值，你感兴趣可以进行评测，欢迎反馈评测结果。

doc中的lio_xyz应该是我测试的三种不同模式的结果，具体是构图还是定位的，我记不清了。

**Comment by LiquoriceH** [comment]
请问输出的odom的频率您当时有没有关注呢，还有您的cpu是什么型号呀

**Comment by chengwei0427** [comment]
没有关注频率

intel i7-10700F 2.9ghz*16   GTX1660Ti
