### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by LiquoriceH** [chengwei0427/Lidar_IMU_Localization#6]
![image](https://user-images.githubusercontent.com/68362652/231735078-4589dedb-d23c-4e14-9ab8-c9c932fe9c7d.png)
作者你好，我没有在Lidar_IMU_Localization中找到cloud_info.h

**Comment by chengwei0427** [comment]
Hi, @LiquoriceH 

感谢关注！这个文件由于疏忽忘记上传了，不过你从liosam拷贝一份过去，就可以了。
