### ISSUE TITLE
关于特征点是否有效

### ISSUE THREAD

**Issue by LiquoriceH** [chengwei0427/Lidar_IMU_Localization#7]
`              if (std::fabs(vLineFeatures[f][cntFtu].error) > 1e-5)
              {
                problem.AddResidualBlock(e, loss_function, para_PR[f]);
                vLineFeatures[f][cntFtu].valid = true;
              }
              else
              {
                vLineFeatures[f][cntFtu].valid = false;
              }`
作者你好，这段代码为什么误差大于1e-5的特征才有效，而不是小于

**Comment by chengwei0427** [comment]
可能会有异常值，所以需要大于一个很小很小1e-5的值。

**Comment by LiquoriceH** [comment]
> 可能会有异常值，所以需要大于一个很小很小1e-5的值。

感谢您的解答
