### ISSUE TITLE
手动给初始位姿后报错，程序没有反应

### ISSUE THREAD

**Issue by 885288421** [chengwei0427/Lidar_IMU_Localization#8]
load map successful...
ROOT_DIR: /home/qt/catkin_ws/src/Lidar_IMU_Localization/
publish corner map,size: 146129
Get initial pose: 0.675896 -0.407225 0 0 -0 0
-----extract surround keyframes ------ 
extractSurroundKeyFrames,takes: 74.9178ms
free(): double free detected in tcache 2
[LIO_Localization_maplocalization-5] process has died [pid 44200, exit code -6, cmd /home/qt/catkin_ws/devel/lib/LIO_Localization/LIO_Localization_maplocalization __name:=LIO_Localization_maplocalization __log:=/home/qt/.ros/log/44814162-ff61-11ed-89a2-4b6b0e2f477c/LIO_Localization_maplocalization-5.log].
log file: /home/qt/.ros/log/44814162-ff61-11ed-89a2-4b6b0e2f477c/LIO_Localization_maplocalization-5*.log
^C[LIO_Localization_rviz-6] killing on exit

**Comment by chengwei0427** [comment]
好像是程序崩溃了啊！
已知，如果初始化定位时，如果给的初始位姿不在点云地图范围内，提取的surround keyframe点云数据为空时，程序会崩溃；你可以加一些打印，或者debug模式看一下哈

**Comment by 885288421** [comment]
我把extractSurroundKeyFrames()改为void,但是在Estimate（）函数中程序依然会挂掉，在通过调试发现问题出在        
std::cout << "21412" << std::endl;
        threads[0].join();
        std::cout << "21512" << std::endl;
        threads[1].join();
        std::cout << "21612" << std::endl;
终端信息：
21412
[LIO_Localization_maplocalization-5] process has died [pid 22842, exit code -11, cmd /home/qt/catkin_ws/devel/lib/LIO_Localization/LIO_Localization_maplocalization __name:=LIO_Localization_maplocalization __log:=/home/qt/.ros/log/19ea1660-ff87-11ed-91fd-a3728bdda469/LIO_Localization_maplocalization-5.log].
log file: /home/qt/.ros/log/19ea1660-ff87-11ed-91fd-a3728bdda469/LIO_Localization_maplocalization-5*.log
可以告诉一下这段代码的具体含义或者如何修改这段代码？谢谢

**Comment by chengwei0427** [comment]
现在重定位成功了吗？

按你目前的打印看，报错出现在threads[0]里面，建议你debug一下吧；

**Comment by 885288421** [comment]
从终端打印的信息来看重定位应该是成功了
load map successful...
ROOT_DIR: /home/qt/catkin_ws/src/Lidar_IMU_Localization/
publish corner map,size: 140498
Get initial pose: -0.0826502 0.0625194 0 0 -0 0.00209498
-----extract surround keyframes ------ 
extractSurroundKeyFrames,takes: 37.6274ms
Change flat from 0 to 1, start do localizating ...
icp takes: 7.97545ms
icp scan match successful ...
make kd-tree: 3.6e-05ms, extract feature: 1.15751ms
可以加个企鹅或者微信吗？debug不会，现在只会cout去查问题，我bilbil私你

**Comment by chengwei0427** [comment]
你构建的kd-tree用时这么少吗？是不是kdtree有问题啊？

如果不会debug，那就需要你多加cout去看看了。

**Comment by 885288421** [comment]
我是运行重定位程序以后，马上开始播包，然后RVIZ中给初始位姿，开始的时候kdtree中数据应该挺少的。是不是应该播包久一点

**Comment by Guoc0529** [comment]
> 我是运行重定位程序以后，马上开始播包，然后RVIZ中给初始位姿，开始的时候kdtree中数据应该挺少的。是不是应该播包久一点

请问你现在解决这个问题了吗，我也遇到了相同 的问题
