### ISSUE TITLE
Device support

### ISSUE THREAD

**Issue by DoongLi** [chengwei0427/Lidar_IMU_Localization#9]
Does this code support Mid360?And can I use the map output of Fast-LIO for localizate?

**Comment by chengwei0427** [comment]
Hi, @DoongLi 
Thanks for interesting in our work!
This project does not support Mid360, but it is easy to extend support.
And you can extend  support the map output of fast-lio for localizating by  changing parts of the code in the same way.
Good luck.

**Comment by DoongLi** [comment]
Can you tell me how to achieve it？

**Comment by chengwei0427** [comment]
You can extend your device  [here](https://github.com/chengwei0427/Lidar_IMU_Localization/blob/cd1fef3a5ae94a9e889c75917a8a8924f1795184/src/lio/featureExtract.cpp#L238C19-L238C19).

**Comment by DoongLi** [comment]
thx chengwei！I will try.
